return Def.ActorFrame{
	FOV=45,
	OnCommand=function(self)
		self:Center()
	end,
	--[[Def.NoteField{
		--NoteSkin="shotrhythm",
		Chart="Challenge",
		DrawDistanceBeforeTargetsPixels=720,
		InitMods="C900",
		FieldID=3,
		--Player=PLAYER_1,
		AutoPlay=true,
		OnCommand=function(self)
			self:rotationx(300):x(64*5)
		end
	},
	Def.NoteField{
		--NoteSkin="shotrhythm",
		Chart="Medium",
		DrawDistanceBeforeTargetsPixels=720,
		InitMods="C900",
		FieldID=4,
		--Player=PLAYER_1,
		AutoPlay=true,
		OnCommand=function(self)
			self:rotationx(300):x(-64*5)
		end
	},--]]
	LoadModule("Gameplay.ComboManager.lua")()
}